### ISSUE TITLE
SASA cannot be calculate ( ./configure --disable-threads)

### ISSUE THREAD

**Issue by blacktanktop** [mittinatten/freesasa#79] opened 2022-05-16 00:52 UTC
Hi!
I configured below,
```./configure --disable-threads --disable-xml --disable-json ```
and I run ```make all```
then the compilation seemed to complete successfully, but I cannot compute SASA. How can I fix this?

```
% freesasa tests/data/1a0q.pdb
## FreeSASA 2.1.0 ##
FreeSASA:sasa_lr.c:178: error: L&R does not support more than 1 threads
FreeSASA:freesasa.c:172: error:
FreeSASA:freesasa.c:176: error:
freesasa: error: can't calculate SASA
```

**Comment by blacktanktop** [comment] 2022-05-16 22:31
thank you for reply
just report above, version 2.03 and version 2.1.0

I just run with  the flag “-t 1” (configure with “—disable-threads”)
```.freesasa -t 1 tests/data/1d3z.pdb ```
then 
```
freesasa: error: option '-t' only defined if program compiled with thread support
```

**Comment by mittinatten** [comment] 2022-05-22 13:23
I could reproduce the error and found the cause. It is fixed in the latest commit.

**Closed** 2022-05-22 13:22 UTC

**Comment by mittinatten** [comment] 2022-05-23 07:02
It is also now part of [FreeSASA 2.1.1](https://github.com/mittinatten/freesasa/releases/tag/2.1.1). Thanks for reporting, it seems this error can have been there a while actually (I guess it's unusual to disable thread support).

**Comment by blacktanktop** [comment] 2022-05-23 10:35
Thank you for update.
(I noticed this error when I disabled threads due to a combination with other software)
