### ISSUE TITLE
Inserted residues

### ISSUE THREAD

**Issue by OlekKuriata** [mittinatten/freesasa#30] opened 2017-10-10 13:51 UTC
For pdb files that contain residues numbered with both a number and a letter (inserted residues), the output pdb file contains those resides, but the generated RSA file only has one residue.
I'm assuming they are all treated as one big residue, which might be an unexpected behavior. 

Example lines from output pdb file: 
ATOM   2488  N   ALA B 100      -5.419  26.119  30.440  1.65  0.18
ATOM   2489  CA  ALA B 100      -3.963  25.990  30.448  1.87  0.44
ATOM   2490  C   ALA B 100      -3.398  26.763  31.633  1.76  1.75
ATOM   2491  O   ALA B 100      -4.033  27.686  32.136  1.40  0.00
ATOM   2492  CB  ALA B 100      -3.379  26.543  29.155  1.87  0.00
ATOM   2493  N   MET B 100A     -2.209  26.376  32.085  1.65  0.34
ATOM   2494  CA  MET B 100A     -1.559  27.077  33.185  1.87  0.00
ATOM   2495  C   MET B 100A     -1.209  28.405  32.517  1.76  0.00
ATOM   2496  O   MET B 100A     -0.245  28.490  31.756  1.40  0.00
ATOM   2497  CB  MET B 100A     -0.320  26.296  33.615  1.87  0.03
ATOM   2498  CG  MET B 100A     -0.677  24.878  34.059  1.87  3.64
ATOM   2499  SD  MET B 100A      0.715  23.813  34.483  1.85  0.46
ATOM   2500  CE  MET B 100A     -0.135  22.301  34.913  1.87  0.82

Output rsa:
RES GLY B  99     0.10   0.1   0.00   N/A   0.10   0.1   0.10   0.2   0.00   0.0
RES ALA B 100     7.66   7.5   4.95   8.9   2.71   5.8   7.14   9.7   0.52   1.8
RES ASP B 101     5.22   3.9   2.23   2.5   2.99   6.6   0.00   0.0   5.22   6.4

**Comment by mittinatten** [comment] 2017-10-10 16:17
Hi, thanks for reporting!
Could you send me an example input file at simon.mitternacht@gmail.com, or post an excerpt with correct whitespace in this thread?

**Comment by mittinatten** [comment] 2017-10-12 13:45
So the problem is the PDB ATOM field iCode is not read by FreeSASA. This should be fixed.

**Comment by mittinatten** [comment] 2017-10-14 08:28
The commit cc480b3c3ac fixes this (dev branch).

**Closed by mittinatten** 2017-10-14 08:28 UTC
